# Generated by Django 3.0.8 on 2021-06-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0002_auto_20210614_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='advance_booking',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='max_guest',
        ),
    ]
